name: Storybook deployment

on:
  push:
    branches:
      - '**'

env:
  BASE_URL: __ENTER_URL__/storybook/
  PULL_REQUEST_NUMBER: ${{ github.event.number }}
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
  GIT_COMMITTER_NAME: ${{ github.actor }}

jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # These lines below are formatted condition for the next `if` condition
#   if !(
#     (github.event_name == 'pull_request' &&
#       (github.event.action == 'closed' || github.event.pull_request.draft == true || contains( github.head_ref, 'dependabot/'))
#     ) ||
#     github.event.pull_request.head.repo.fork
#   )
    if: false == ( ( github.event_name == 'pull_request' && ( github.event.action == 'closed' || github.event.pull_request.draft == true || contains( github.head_ref, 'dependabot/' ) ) ) || github.event.pull_request.head.repo.fork )
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Cache Node - npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-

      - name: yarn install
        run: |
          yarn install

      - name: Build Storybook
        run: |
          yarn build:storybook

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: storybook-files
          path: dist

  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: build-storybook
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Set env vars
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/*/}
          echo ::set-output name=BRANCH_NAME::${BRANCH_NAME//\//-}

      - name: Download artifacts
        id: download-artifacts
        uses: actions/download-artifact@v1
        with:
          name: storybook-files
          path: dist

      - name: Set branch environment variables
        id: branch-target
        if: github.event_name != 'pull_request'
        run: |
          echo "::set-output name=dir::${{ steps.vars.outputs.BRANCH_NAME }}"

      - name: Set PR environment variables
        id: pr-target
        if: github.event_name == 'pull_request'
        run: |
          echo "::set-output name=dir::pull/${PULL_REQUEST_NUMBER}"

      - name: Commit updates
        run: |
          mkdir -p storybook/${TARGET_DIR}
          rm -rf storybook/${TARGET_DIR}
          mv dist storybook/${TARGET_DIR}
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Deploy storybook for ${TARGET_DIR}."
          git push origin gh-pages
        env:
          TARGET_DIR: ${{ steps.branch-target.outputs.dir }}${{ steps.pr-target.outputs.dir }}

      - name: Display list of available deployments
        run: |
          cd storybook && for d in *; do echo ${BASE_URL}${d} ;done

      - uses: mshick/add-pr-comment@v1
        with:
          message: Storybook for branch `${{ steps.vars.outputs.BRANCH_NAME }}` is [deployed](${{ env.BASE_URL }}${{ env.TARGET_DIR }}) 🎉🎉
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # The user.login for temporary GitHub tokens (github-actions[bot] is available natively)
          repo-token-user-login: 'github-actions[bot]'
        env:
          TARGET_DIR: ${{ steps.branch-target.outputs.dir }}${{ steps.pr-target.outputs.dir }}

  remove-storybook:
    name: Remove Storybook
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.pull_request.merged == 'true' || (( github.event_name == 'pull_request' && github.event.action == 'closed' && contains( github.head_ref, 'dependabot/' ) == false ) && github.event.pull_request.head.repo.fork == false)
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Remove storybook
        run: |
          git rm -rf storybook/pull/${PULL_REQUEST_NUMBER}
          git rm -rf storybook/${GITHUB_REF##*/}
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Remove storybook for pull/${PULL_REQUEST_NUMBER}."
          git push origin gh-pages
